### ISSUE TITLE
Taking a screenshot should copy the data to the clipboard

### ISSUE THREAD

**Issue by sonnyp** [sonnyp/Workbench#298]
# Description

On GNOME Shell, after taking a screenshot, the user is presented with

![image](https://github.com/sonnyp/Workbench/assets/19673/2cfed9db-b808-49d9-a56b-1b045c9ed0f1)

Workbench has a button to take a screenshot of the preview. It works similarly except it doesn't work the data to the clipboard for a quick pasting.

We should align with this and also the notification subtitle.

# Todo

* [x] Copy the screenshot data into the clipboard so it can be pasted into an image editor such as Gimp for example
* [x] Adjust the notification title to say "Workbench Screenshot captured"
* [x] Adjust the notification subtitle to say "You can paste the image from the clipboard."

You can find the relevant function in `Previewer.js`
